---
kind: pipeline
type: kubernetes
name: pr

trigger:
  event:
    - pull_request

steps:
  - name: wait for docker
    image: docker
    commands:
      - timeout 15s /bin/sh -c 'while [ ! -S /var/run/docker.sock ]; do sleep 1; done'
      - docker version
    volumes:
      - name: dockersock
        path: /var/run
  - name: build images
    image: docker:git
    commands:
      - apk add --no-cache make bash
      - make images
    volumes:
      - name: dockersock
        path: /var/run

services:
  - name: run docker daemon
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
type: kubernetes
name: publish

trigger:
  branch:
    - master
  event:
    - push
    - cron

steps:
  - name: wait for docker
    image: docker
    commands:
      - timeout 15s /bin/sh -c 'while [ ! -S /var/run/docker.sock ]; do sleep 1; done'
      - docker version
    volumes:
      - name: dockersock
        path: /var/run
  - name: build images
    image: docker:git
    commands:
      - apk add --no-cache make bash
      - make images
    volumes:
      - name: dockersock
        path: /var/run
  - name: publish images
    image: docker:git
    environment:
      USERNAME:
        from_secret: quay_username
      PASSWORD:
        from_secret: quay_password
    commands:
      - apk add --no-cache make bash
      - docker login -u="$USERNAME" -p="$PASSWORD" quay.io
      - make push
    volumes:
      - name: dockersock
        path: /var/run

services:
  - name: run docker daemon
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
---
kind: signature
hmac: 656239b161f47eada785e2e4b3b0829c74b8a8e517a37da410b422989ed1f2a6

...
